osx_image: osx_image: xcode11.6
language: swift
os: osx
xcode_project: Numero.xcodeproj
xcode_scheme: Numero
xcode_destination: platform=iOS Simulator, OS=13.6, name=iPhone 8
script: xcodebuild clean build test -project Numero.xcodeproj -scheme "Numero" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=13.6,name=iPhone 8" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
